# Generated by Django 4.1.3 on 2022-11-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benson',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('part_number', models.TextField(blank=True, null=True, verbose_name='Part Number')),
                ('product', models.TextField(blank=True, null=True, verbose_name='PRODUCT')),
                ('color', models.TextField(blank=True, null=True, verbose_name='COLOR')),
                ('vehicle', models.TextField(blank=True, null=True, verbose_name='VEHICLE')),
            ],
        ),
    ]
